apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-ip.fullname" . }}-config
data:
  TYPE: "{{ .Values.app.type }}"
  PORT: "{{ .Values.app.port }}"
  POSTGRES_HOST: "{{ .Values.postgresql.host.postgresql }}"
  POSTGRES_PORT: "{{ .Values.postgresql.primary.service.ports.postgresql }}"
  POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
  POSTGRES_DB: "{{ .Values.postgresql.auth.database }}"
