apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-ip.fullname" . }}
spec:
  selector:
    app: {{ include "fastapi-ip.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
  type: {{ .Values.service.type }}
